

services:
  manager_agent:
    build: ./manager_agent
    ports:
      - "8000:8000"
    depends_on:
      - process_verifier
      - parser

  process_verifier:
    build: ./sub_agents/process_verifier
    ports:
      - "5001:5000"

  parser:
    build: ./sub_agents/parser
    ports:
      - "5002:5000"
